### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by jcat4**
This fixes a few typos I found in the introduction.

### CODE REVIEW

**Review by IsaacG — APPROVED** [review]

**Comment by IsaacG** [comment]
+cc @mea

**Comment by meatball133** [comment]
Changes should also be applied to the following files:

- concept:characters-and-strings:about.md
- exercise:characters-and-strings:introduction.md

Otherwise, the changes look good!

**Comment by jcat4** [comment]
Alright, I've made the changes to the files you pointed out

**Comment by IsaacG** [comment]
+cc @exercism/swift

**Review by meatball133 — APPROVED** [review]

**Pull request merged**
