### PR TITLE
Rotational cipher

### PR DESCRIPTION
**Pull request by creaaa**
Dear repository master,

Hello, I'm Masa, an iOS developer.
I was impressed by this project and added(ported) a new exercise. It's "Rotational cipher".

Would you take a look and merge if there's no problem?
I'm happy to fix my code if I'm making a mistake.

Thanks,
Masa

### CODE REVIEW

**Comment by creaaa** [comment]
Dear maintainers,

Hello, I was making a mistake. I was overlooking about swiftlint and Travis CI.
Now lint doesn't complain about rotational-cipher directory I added and passed Travis CI as you can see.
Again, could you take a look? I’m sorry to bother you.


Sincerely,
Masa

**Comment by masters3d** [comment]
Hi Masa!

Thanks for the contribution. A couple of small changes otherwise looks great!

Thanks.

**Comment by masters3d** [comment]
Sorry, I forgot to push my comments. :(

**Comment by creaaa** [comment]
Dear Jose,

I have to say thank you for your courteous code review.
Then I re-fixed some code so that it met repository’s requirement.
As you can see, swiftlint complaints nothing and passes Travis CI.
Would you take a look and let me know if I have some problem with that?

Thanks in advance.

sincerely,
Masa

**Comment by masters3d** [comment]
Thank you!

**Comment by creaaa** [comment]
I really appreciated it, Jose! 😭

**Pull request merged**
