### PR TITLE
Incorrect example operator

### PR DESCRIPTION
**Pull request by K4zMa**
Fixed the values for the less than operator in the introduction to comparision operators.

### CODE REVIEW

**Comment by meatball133** [comment]
Changes should also be applied to the following files:

concept:conditionals:about.md
exercise:vehicle-purchase:introduction.md

**Comment by K4zMa** [comment]
thanks for pointing it out

**Comment by meatball133** [comment]
Forgot to add that the change also have to be applied to:

- concept:conditionals:introduction.md

**Comment by K4zMa** [comment]
already done

**Review by meatball133 — APPROVED** [review]

**Pull request merged**
