### PR TITLE
Updated concept docs and the docs

### LINKED ISSUE #475: Check docs are up to date
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- `docs/ABOUT.md`
- `docs/INSTALLATION.md`
- `docs/LEARNING.md`
- `docs/RESOURCES.md`
- `docs/TESTS.md`
- `exercises/shared/.docs/help.md`
- `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total..........197
✅ Successful.....197
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........0

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

### PR DESCRIPTION
**Pull request by meatball133**
Resolves #475

### CODE REVIEW

**Comment by meatball133** [comment]
There is although a website which seems to be deprecated which we are still linking to: [formatSpecifiers](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html)

**Review by ErikSchierboom — APPROVED** [review]
Nice work!

**Comment by ErikSchierboom** [comment]
Let me know when you're ready to have this merged

**Comment by meatball133** [comment]
Out of the [formatSpecifiers](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/Strings/Articles/formatSpecifiers.html) seem bit outdated, I feel like the links are now up to date. I removed the link to swift education because it said the website was deprecated and replaced it with swift playground, I know it is a bit child themed but they have some nice tutorial on swift ui

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
