### PR TITLE
Add ISBN Verifier exercise

### PR DESCRIPTION
**Pull request by robtimp**
* Add ISBN Verifier exercise in Swift

### CODE REVIEW

**Comment by robtimp** [comment]
@masters3d

**Comment by robtimp** [comment]
@masters3d Any idea why the Linux Swift 4 build fails?

**Comment by masters3d** [comment]
I guess we need to update the docker image:
https://hub.docker.com/r/norionomura/swift/tags/

**Comment by masters3d** [comment]
We should probably use official images
https://hub.docker.com/r/library/swift/tags/
4.0.2 looks good.

**Pull request merged**
