### PR TITLE
moved danger and macOS to circle

### PR DESCRIPTION
**Pull request by masters3d**
- Steps to remove travisCI mac

### CODE REVIEW

**Comment by masters3d** [comment]
Hi @kytrinyx , 

Little help here. I am trying to have Circle CI kick for every build for macOS. I do not have permission to edit this on CircleCI's website. Travis got to be way to slow for macBuilds.

Thanks

**Comment by masters3d** [comment]
I am going to merge to see if that changes something.

**Comment by masters3d** [comment]
@kytrinyx Please disregard. :)

**Comment by kytrinyx** [comment]
Glad you got it sorted!

**Pull request merged**
