### PR TITLE
Resize polar_to_cartesian image, update image path to fix 404, and move to img folder

### PR DESCRIPTION
**Pull request by wsaults**
Proposed fix for:
Decreasing size of polar_to_cartesian.svg image and nesting inside an img folder.

Note: Added `./` to image path ie: `./img/polar_to_cartesian.png`. This fixes the 404 error.

### CODE REVIEW

**Review by ErikSchierboom — COMMENTED** [review]
This won't work, neither on the website nor locally (the `.docs` directory is ignored). The image _has_ to be to an external site.

**Comment by wsaults** [comment]
@ErikSchierboom, gotcha. I'll see if I can find a replacement. What about using an image hosting service? https://postimages.org/ or similar?

**Comment by ErikSchierboom** [comment]
@iHiD What would the appropriate location for an external image be?

**Comment by iHiD** [comment]
`https://exercism-static.s3.eu-west-1.amazonaws.com/content/polar_to_cartesian.png`

**Comment by ErikSchierboom** [comment]
@wsaults See the above comment for the correct location.

**Comment by wsaults** [comment]
@ErikSchierboom PR has been updated with the new url.

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
