### PR TITLE
Re-order tests for SecretAgent exercise

### PR DESCRIPTION
**Pull request by lukaszklis**
Based on the current structure of the `SecretAgentTests.swift`, Exercism users would have to implement the `protectSecret` function before being able to execute `generateCombination`’s tests ([unless the test file has lines references commented out](https://github.com/lukaszklis/swift/blob/45a243db3e442c33dc7878e542d140ad7f77560c/exercises/concept/secret-agent/Tests/SecretAgentTests/SecretAgentTests.swift#L7-L8)).

In order to make the users’ journey easier, I swapped the order of what has to be implemented.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
Nice quality of life improvement!

**Comment by ErikSchierboom** [comment]
I do see a build failure:

```
/Users/runner/work/swift/swift/exercises/concept/secret-agent/Tests/SecretAgentTests/SecretAgentTests.swift:15:5: error: errors thrown from here are not handled
    try XCTSkipIf(true && !runAll)  // change true to false to run this test
```

**Comment by lukaszklis** [comment]
Just seen it. I must have forgotten to add `throws` in the test function definition. Will push a fix in a moment. Sorry about that!

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
